apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-1
  description: 'Cloud Gaming Test 1 Service'
  tags:
    - golang
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: 'group:infra-support'
  providesApis:
    - test-1-api
