site_name: 'Test 1'
site_description: 'test-1'

theme:
  features:
    - tabs
  name: material
  icon:
    logo: material/cloud
  font:
    text: Ubuntu
    code: Ubuntu Mono
  static_templates:
    - 404.html

plugins:
  - techdocs-core
